libraries, autospec: refactoring library loading to fix some issues
Signed-off-by: Davide Madrisan <davide.madrisan@gmail.com>

diff --git a/autospec.in b/autospec.in
--- a/autospec.in
+++ b/autospec.in
@@ -20,11 +20,10 @@
 
 me=(${0##*/} "@version@" "@date@")
 
-if [[ -z "$LANG" && -r /etc/sysconfig/i18n ]]; then
-   . /etc/sysconfig/i18n
-   [ "$LANG" ] && export LANG
-fi
-TEXTDOMAIN="@package@"; export TEXTDOMAIN
+[ -r @libdir@/libtranslate.lib ] ||
+ { echo "$me: "$"library not found"": @libdir@/libtranslate.lib" 1>&2
+   exit 1; }
+. @libdir@/libtranslate.lib
 
 # default values
 let "pck_update = 0"
