libapse.lib: use libtranslate.lib
Signed-off-by: Davide Madrisan <davide.madrisan@gmail.com>

diff --git a/lib/libapse.lib.in b/lib/libapse.lib.in
--- a/lib/libapse.lib.in
+++ b/lib/libapse.lib.in
@@ -21,11 +21,10 @@ me=("libapse.lib" "@version@" "@date@")
    exit 1; }
 . @libdir@/libspec.lib
 
-if [[ -z "$LANG" && -r /etc/sysconfig/i18n ]]; then
-   . /etc/sysconfig/i18n
-   [ "$LANG" ] && export LANG
-fi
-TEXTDOMAIN="@package@"; export TEXTDOMAIN
+[ -r @libdir@/libtranslate.lib ] ||
+ { echo "$me: "$"library not found"": @libdir@/libtranslate.lib" 1>&2
+   exit 1; }
+. @libdir@/libtranslate.lib
 
 # function apse.cmpversion()
 #    compare two version
