libtranslate.lib: new library
Signed-off-by: Davide Madrisan <davide.madrisan@gmail.com>

diff --git a/lib/libmsgmng.lib.in b/lib/libmsgmng.lib.in
--- a/lib/libmsgmng.lib.in
+++ b/lib/libmsgmng.lib.in
@@ -8,11 +8,12 @@ libmsgmng_is_loaded=1
 [ -z "$BASH" ] || [ ${BASH_VERSION:0:1} -lt 2 ] &&
    echo $"this script requires bash version 2 or better" >&2 && exit 1
 
-if [[ -z "$LANG" && -r /etc/sysconfig/i18n ]]; then
-   . /etc/sysconfig/i18n
-   [ "$LANG" ] && export LANG
-fi
-TEXTDOMAIN="@package@"; export TEXTDOMAIN
+me=("libmsgmng.lib" "@version@" "@date@")
+
+[ -r @libdir@/libtranslate.lib ] ||
+ { echo "$me: "$"library not found"": @libdir@/libtranslate.lib" 1>&2
+   exit 1; }
+. @libdir@/libtranslate.lib
 
 # notify family of message handling functions:
 #  - notify.warning
diff --git a/lib/libspec.lib.in b/lib/libspec.lib.in
--- a/lib/libspec.lib.in
+++ b/lib/libspec.lib.in
@@ -8,16 +8,17 @@ libspec_is_loaded=1
 [ -z "$BASH" ] || [ ${BASH_VERSION:0:1} -lt 2 ] &&
    echo $"this script requires bash version 2 or better" >&2 && exit 1
 
+me=("libspec.lib" "@version@" "@date@")
+
 [ -r @libdir@/libmsgmng.lib ] ||
  { echo "$me: "$"library not found"": @libdir@/libmsgmng.lib" 1>&2
    exit 1; }
 . @libdir@/libmsgmng.lib
 
-if [[ -z "$LANG" && -r /etc/sysconfig/i18n ]]; then
-   . /etc/sysconfig/i18n
-   [ "$LANG" ] && export LANG
-fi
-TEXTDOMAIN="@package@"; export TEXTDOMAIN
+[ -r @libdir@/libtranslate.lib ] ||
+ { echo "$me: "$"library not found"": @libdir@/libtranslate.lib" 1>&2
+   exit 1; }
+. @libdir@/libtranslate.lib
 
 # function boolexpr.solve
 #    calculate the boolean expression `$1' expanding the variables
diff --git a/plugins/spec-create.in b/plugins/spec-create.in
--- a/plugins/spec-create.in
+++ b/plugins/spec-create.in
@@ -66,11 +66,10 @@ preserve_dot_git=0
    exit 1; }
 . @libdir@/libcfg.lib
 
-if [[ -z "$LANG" && -r /etc/sysconfig/i18n ]]; then
-   . /etc/sysconfig/i18n
-   [ "$LANG" ] && export LANG
-fi
-TEXTDOMAIN="@package@"; export TEXTDOMAIN
+[ -r @libdir@/libtranslate.lib ] ||
+ { echo "$me: "$"library not found"": @libdir@/libtranslate.lib" 1>&2
+   exit 1; }
+. @libdir@/libtranslate.lib
 
 function copying() {
    echo "\
diff --git a/tests/test00_specsyntax.in b/tests/test00_specsyntax.in
--- a/tests/test00_specsyntax.in
+++ b/tests/test00_specsyntax.in
@@ -5,17 +5,18 @@
 [ -z "$BASH" ] || [ ${BASH_VERSION:0:1} -lt 2 ] &&
    echo $"this script requires bash version 2 or better" >&2 && exit 1
 
+me=("test00_specsyntax" "@version@" "@date@")
+
 [ -r @libdir@/libmsgmng.lib ] ||
  { echo "$me: "$"library not found"": @libdir@/libmsgmng.lib" 1>&2
    exit 1; }
 
 . @libdir@/libmsgmng.lib
 
-if [[ -z "$LANG" && -r /etc/sysconfig/i18n ]]; then
-   . /etc/sysconfig/i18n
-   [ "$LANG" ] && export LANG
-fi
-TEXTDOMAIN="@package@"; export TEXTDOMAIN
+[ -r @libdir@/libtranslate.lib ] ||
+ { echo "$me: "$"library not found"": @libdir@/libtranslate.lib" 1>&2
+   exit 1; }
+. @libdir@/libtranslate.lib
 
 # check if all the needed tools are available
 for tool in cat file getopt grep sed; do
