translation framework: xgettext is buggy: use 'bash --dump-po-strings' instead and rework all the code
Signed-off-by: Davide Madrisan <davide.madrisan@gmail.com>

diff --git a/po/it/Makefile b/po/it/Makefile
--- a/po/it/Makefile
+++ b/po/it/Makefile
@@ -18,7 +18,20 @@ srcdir = ../..
 
 include $(srcdir)/Makefile.env
 
-pck_catalogs := $(wildcard *.po)
+pck_catalogs_tmpl := autospec_fe.pot \
+   config-getvar.pot \
+   libapse.pot \
+   libcfg.pot \
+   libmsgmng.pot \
+   libnetwork.pot \
+   libspec.pot \
+   libtest.pot \
+   pck-extract.pot \
+   pck-update.pot \
+   spec-create.pot \
+   test00_specsyntax.pot \
+   test01_pkgquality.pot \
+   test02_pkgsecurity.pot
 
 LANG=it
 
@@ -29,29 +42,30 @@ LANG=it
 
 all: locales
 
-locales: $(pck_catalogs:.po=.mo)
-
 pck_manpages := 
 
-pot-merge: $(patsubst %.po,%.pot,$(wildcard $(srcdir)/po/*.po))
-	@for f in $(pck_catalogs:.po=); do\
-	   echo "Merging '$$f.po' with '$$f.pot'...";\
-	   /usr/bin/msgmerge --update --no-wrap \
-	      $$f.po $(srcdir)/po/$$f.pot;\
-	done
+merge-pot-files: $(patsubst %,$(srcdir)/po/%,$(pck_catalogs_tmpl))
+	@echo "Creating global pot file...";\
+	/bin/cat $(patsubst %,$(srcdir)/po/%,$(pck_catalogs_tmpl)) \
+	   > $(srcdir)/po/$(PACKAGE)-all.pot;\
+	/usr/bin/msguniq --use-first --no-location --no-wrap \
+	   $(srcdir)/po/$(PACKAGE)-all.pot \
+	   -o $(srcdir)/po/$(PACKAGE).pot && \
+	   echo "... $(PACKAGE)-all.pot [PASSED]" || \
+	   { echo ".. $(PACKAGE)-all.pot [FAILED]"; exit 1; }
 
-locales-concatenate: pot-merge
-	@echo "Concatenating locales...";\
-	/usr/bin/msgcat $(pck_catalogs:.po=) -o $(PACKAGE)-all.po;\
+locales: merge-pot-files
+	@echo "Generating global locale...";\
+	/usr/bin/msgmerge --update --no-fuzzy-matching --indent \
+	   $(PACKAGE).po \
+	   $(srcdir)/po/$(PACKAGE).pot;\
 	echo "... $(PACKAGE)-all.po [DONE]"
+	
 
 install: locales
 	@destdir="$(DESTDIR)$(localedir)/$(LANG)/LC_MESSAGES";\
 	$(INSTALL_DIR) $$destdir;\
-	$(INSTALL_DATA) $(PACKAGE)-all.mo $$destdir/$(PACKAGE)-all.mo
-	#for f in $(pck_catalogs:.po=); do\
-	#   $(INSTALL_DATA) $${f}.mo $$destdir/$${f}.mo;\
-	#done
+	$(INSTALL_DATA) $(PACKAGE).mo $$destdir/$(PACKAGE).mo
 
 uninstall:
 	@for f in $(pck_catalogs:.po=); do\
